openapi: 3.0.1
info:
  title: Passive Product Service API
  version: 1.1.0
  description: Microservice for managing bank passive products.

servers:
  - url: http://localhost:8082

paths:

  /:
    get:
      summary: Get all passive products (only active)
      tags: [PassiveProduct]
      responses:
        "200":
          description: List of active products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PassiveProduct"

    post:
      summary: Create a passive product
      tags: [PassiveProduct]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PassiveProductRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PassiveProduct"

  /{id}:
    get:
      summary: Get product by ID (only active)
      tags: [PassiveProduct]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Active product found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PassiveProduct"
        "404":
          description: Not found

    put:
      summary: Update passive product
      tags: [PassiveProduct]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PassiveProductRequest"
      responses:
        "200":
          description: Updated product

    delete:
      summary: Soft delete passive product
      tags: [PassiveProduct]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "204":
          description: Soft deleted

  /{id}/balance:
    get:
      summary: Get balance of product
      tags: [PassiveProduct]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Balance
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponse"
    patch:
      summary: Update product balance
      tags: [ PassiveProduct ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BalanceUpdateRequest"
      responses:
        "200":
          description: Balance updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PassiveProduct"
        "400":
          description: Invalid request (e.g. credit limit exceeded)


  /customer/{customerId}:
    get:
      summary: Get all active passive products for a specific customer
      tags: [PassiveProduct]
      parameters:
        - in: path
          name: customerId
          required: true
          schema: { type: string }
        - in: query
          name: id
          required: false
          schema: { type: string }
      responses:
        "200":
          description: List of products for the customer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PassiveProduct"
        "404":
          description: Customer not found or no products




components:
  schemas:

    PassiveProduct:
      type: object
      required: [id, customerId, accountType, balance]
      properties:
        id:
          type: string
        customerId:
          type: string
        accountType:
          type: string
          enum: [SAVING, CURRENT, FIXED_TERM]
        balance:
          type: number
        transactionLimit:
          type: integer
        maintenanceFee:
          type: number
        allowedMovementDay:
          type: integer
        active:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time

    PassiveProductRequest:
      type: object
      required: [customerId, accountType]
      properties:
        customerId:
          type: string
        accountType:
          type: string
          enum: [SAVING, CURRENT, FIXED_TERM]

    BalanceResponse:
      type: object
      properties:
        balance:
          type: number
    BalanceUpdateRequest:
      type: object
      required: [amount]
      properties:
        amount:
          type: number